# .prettierrc.toml
trailingComma = "all"
tabWidth = 2
semi = false
singleQuote = true
jsxSingleQuote = true
printWidth = 120
bracketSameLine = false
arrowParens = "always"
endOfLine = "crlf"
plugins = ["prettier-plugin-tailwindcss"]